### ISSUE TITLE
EPIC: Build Admin UI for Updates (mostly frontend)

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156/proj-courses#145]
## User Story

* As an admin
* I can see a nicely formatted table with the contents of the updates
* So that I can manage the updates to the course data

# Discussion

There is a backend endpoint for showing when the MongoDB version of the data for each subject area was last updated from the UCSB API:

<img width="752" alt="image" src="https://github.com/user-attachments/assets/f7896237-9f33-44c0-99b8-8b0ad3542a90">

The json it returns looks like this:

```json
{
      "_id": {
        "timestamp": 1731206250,
        "date": "2024-11-10T02:37:30.000+00:00"
      },
      "subjectArea": "GRAD W",
      "quarter": "20244",
      "saved": 0,
      "updated": 0,
      "errors": 0,
      "lastUpdate": "2024-11-10T02:37:30.677"
    },
    {
      "_id": {
        "timestamp": 1731206250,
        "date": "2024-11-10T02:37:30.000+00:00"
      },
      "subjectArea": "IQB",
      "quarter": "20244",
      "saved": 11,
      "updated": 36,
      "errors": 0,
      "lastUpdate": "2024-11-10T02:37:30.467"
    },
    {
      "_id": {
        "timestamp": 1731206246,
        "date": "2024-11-10T02:37:26.000+00:00"
      },
      "subjectArea": "W&L  CSW",
      "quarter": "20244",
      "saved": 0,
      "updated": 0,
      "errors": 0,
      "lastUpdate": "2024-11-10T02:37:26.354"
    },
```

However, there is no user interface for this.

Working one issue, at a time, in separate PRs, build this page step-by-step:

- [ ] Add a new page that should be available only to Admins called AdminUpdatesPage (at first a placeholder page, available from a new menu item in the Admin menu "Updates")
- [ ] Make a UpdateTable component for updates that displays these columns: Subject Area, Quarter (format it as QXX, not YYYYQ), saved, updated, errors, and last update), with tests and stories.
- [ ] Make DropdownSelector components that allows the user to select a subject area, or ALL, and a quarter START_QTR and END_QTR or ALL.     Note that there are existing QuarterSelector and SubjectAreaSelectors, but they don't have an ALL option.  One option is to add a prop to the existing selectors `showAll` with a default value of `false`, and then add storybook stories showing the two versions.  You need to ensure that your addition is backwards compatible.  OR, you can create entirely separate components.
- [ ] Incorporate the dropdowns and the table so that the Update page now has all of the features of the Update backend.  Include a page selector so that you can page through the updates if needed, and set the size of the pages to 10, 50, or 100.
