### ISSUE TITLE
FEATURE: Automatic caching of data

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156/proj-courses#34]
# User Stories

* As a user
* I can always know that I'm seeing the latest data
* So that I have confidence in the application

### Discussion

At the moment, the app has two ways of fetching data:

* The main page uses live data from the UCSB Developer API.  The advantage here is that the data is always up to date, and no preloading of databases is needed.  The disadvantage is that queries such as "by instructor", "course over time", etc. are not supported.
* Other pages use data that was pre-loaded into the MongoDB database.  The advantage is performance (may be faster than the UCSB Developer API since data is on the same machine), and a wider range of queries we can support.  The disadvantage is that data must be pre-fetched.

What if we could have the best of both worlds?

That is: 
* Every time someone does a search on the main page we still use the live API, but we *also* take the data we get and "upsert it" into the MongoDb database (meaning we update the data if it's there, insert it if it isn't there.
* Every time someone does a search on a page that relies on the MongoDB database, we check the quarters and subject areas they are looking for.  If we haven't yet retrieved the data for those quarter and subject areas, we do two things: 
  - Alert the user that the data for that quarter/subject area is not yet available
  - Invite the user to check back in a few minutes
  - Kick off the background job to update that data.

### Acceptance Criteria

This is a partial list: as this issue is broken down into more fine grained issues, additional acceptance criteria may be needed.

- [ ] Searches on the front page work as before, but data from queries to the backend is upserted into MongoDB.
- [ ] Searches on the pages that use MongoDB provide warnings when the data is not yet available (this could be done first, separately from the steps below.)
- [ ] Not only does the user get a message when data to support the search is not available, a job to update that data is submitted, and the user is invited to check back in 5 minutes.

**Comment by pconrad** [comment]
# Implementation Plan: Automatic caching of data (#34)

*Prepared from a code audit of the repo as of 2026-08-20. All file paths are
relative to the repo root. Verified by direct file reads, not just search
results.*

## TL;DR

Most of the hard infrastructure for this issue **already exists**. Nothing
described below requires new schema/entities. The work is entirely about
*wiring existing pieces together* in two controllers, plus a small amount of
new frontend UI.

| Piece the issue needs | Status |
|---|---|
| Table tracking last-updated time per (subjectArea, quarter) | ✅ Already exists — `Update` document / `updates` collection |
| Staleness logic (is this data missing or old?) | ✅ Already exists — `IsStaleService` |
| Job that fetches live data and upserts it into Mongo | ✅ Already exists — `UpdateCourseDataJob` |
| Way to launch that job for one subject+quarter | ✅ Already exists — `UpdateCourseDataJobFactory` + `JobService.runAsJob` — but only reachable via an **admin-only** endpoint |
| Live main-page controller upserting its own results into Mongo | ❌ Missing |
| Mongo-backed pages checking freshness and warning the user | ❌ Missing |
| Non-admin-safe way to trigger a background load | ❌ Missing |

So this issue is really two independent, separable sub-features. Recommend
splitting into two child issues (the acceptance criteria already suggest
this ordering):

- **#34a — Freshness warning on MongoDB-backed pages** (read-only, safer, do first)
- **#34b — Auto-upsert of live API results into MongoDB** (write path, do second)

---

## Background: the pieces that already exist

- **`Update` document** — `src/main/java/edu/ucsb/cs156/courses/documents/Update.java`
  Fields: `subjectArea`, `quarter`, `saved`, `updated`, `errors`, `lastUpdate`.
- **`UpdateCollection`** — `src/main/java/edu/ucsb/cs156/courses/collections/UpdateCollection.java`
  `findBySubjectAreaAndQuarter`, `findByQuarter`, `findBySubjectArea`, `findAll`.
- **`UpdateService.getLastUpdate(subjectArea, quarterYYYYQ)`** —
  `src/main/java/edu/ucsb/cs156/courses/services/UpdateService.java` (lines 28-42)
  Returns `Optional<LocalDateTime>`, empty if that combo has never been loaded.
- **`IsStaleService.isStale(subjectArea, quarterYYYYQ)`** —
  `src/main/java/edu/ucsb/cs156/courses/services/IsStaleService.java`
  `true` if never loaded, if a past quarter's last update predates the
  quarter's last day of schedule, or if a current/future quarter's last
  update is older than `app.courseDataStaleThresholdMinutes` (default 1440 =
  24h).
- **`UpdateCourseDataJob`** — `src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataJob.java`
  Calls `UCSBCurriculumService.getConvertedSections(subjectArea, quarterYYYYQ, "A")`
  (the live API) and upserts each result into `ConvertedSectionCollection`
  (`updateCourses`, lines 71-116), then writes a new `Update` record
  (`updateUpdatesCollection`, lines 64-69). **This is exactly the upsert
  logic issue #34 asks for** — it's just not invoked from a live user
  request today.
- **`UpdateCourseDataJobFactory`** — builder methods
  `createForSubjectAndQuarterAndIfStale(subjectArea, quarterYYYYQ, ifStale)`
  etc.
- **`JobsController`** (`src/main/java/edu/ucsb/cs156/courses/controllers/JobsController.java`)
  exposes `POST /api/jobs/launch/updateCourses` etc., all
  `@PreAuthorize("hasRole('ROLE_ADMIN')")`.
- **`ScheduledJobs`** already runs `UpdateCourseDataJob` on a cron for the
  current+future quarters (`ifStale=true`), so common cases self-heal over
  time — the acute problem is a user hitting a subject/quarter combo that
  hasn't been loaded *yet*.

### Data model note for whoever implements this

`Update.subjectArea` is the bare subject code (e.g. `"CMPSC"`), matching
`UCSBSubject.subjectCode`. `ConvertedSection.courseInfo.courseId` is instead
a padded 8-char field (e.g. `"CMPSC   130A"`). Any new code that needs to go
from a `ConvertedSection` query back to a `subjectArea` string for staleness
lookup should reuse whatever subject-area parameter the controller already
receives as a request param (all four `CourseOverTime*` controllers already
take `subjectArea` as an explicit `@RequestParam`) rather than trying to
parse it out of `courseId`.

---

## Part 1 (do first): Freshness warning on MongoDB-backed pages

**Goal:** when a user searches `CourseOverTime*` pages for a subject/quarter
combo that has never been loaded (or is stale), tell them so and kick off a
background load, instead of silently returning an empty/incomplete list.

### Backend changes

Controllers to change (all in `src/main/java/edu/ucsb/cs156/courses/controllers/`):
- `CourseOverTimeController` (`/api/public/courseovertime/search`)
- `CourseOverTimeInstructorController` (`/api/public/courseovertime/instructorsearch`)
- `CourseOverTimeDescriptionController` (`/api/public/description/search`)
- `CourseOverTimeBuildingController` (`/api/public/courseovertime/buildingsearch`, `/classrooms`)

Each of these queries a **range** of quarters (`startQtr`/`endQtr`), so
"freshness" isn't a single boolean — it's per-quarter-in-range. Suggested
approach:

1. Add a small shared helper, e.g. `FreshnessService` (new class in
   `services/`), with a method like:
   ```java
   record FreshnessInfo(List<String> missingOrStaleQuarters) {}
   FreshnessInfo checkFreshness(String subjectArea, String startQtr, String endQtr)
   ```
   It iterates `Quarter.quarterList(startQtr, endQtr)` (reuse the same
   helper `UpdateCourseDataJob` uses) and calls
   `isStaleService.isStale(subjectArea, quarterYYYYQ)` for each, collecting
   the ones that are stale/missing. Keep this as its own service so it isn't
   duplicated four times across controllers, and so it's independently unit
   testable.

2. Change each controller's response shape from a bare `List<ConvertedSection>`
   / raw JSON string to an envelope that includes both the results and a
   freshness flag, e.g.:
   ```java
   record CourseOverTimeResponse(
       List<ConvertedSection> results,
       List<String> staleOrMissingQuarters)
   ```
   **This is a breaking API change for existing frontend callers** — plan
   the frontend change in the same PR (see below), and update
   `frontend/src/utils/*.js` fetch helpers + tests together with the
   controller. Check `docs/openapi.yaml` (if the project generates it) and
   regenerate/update after changing the response shape.

3. When `staleOrMissingQuarters` is non-empty, launch a background job for
   just those quarters so the data self-heals for the *next* request. This
   needs a **non-admin-safe** trigger:
   - Do **not** reuse the existing `ROLE_ADMIN`-gated `JobsController`
     endpoints directly from a public controller in-process — that's fine
     (it's just a Java method call, not an HTTP round-trip through Spring
     Security), but do add rate limiting / de-duplication so that N
     concurrent public requests for the same missing subject/quarter don't
     launch N redundant jobs. `JobRateLimit` already exists and is injected
     into `UpdateCourseDataJob` for spacing out UCSB API calls *within* a
     job, but nothing currently guards against launching the *same* job
     twice concurrently from two public requests.
     - Simplest option: an in-memory `ConcurrentHashMap<String, Boolean>` or
       a short-TTL cache keyed by `subjectArea+quarter` that gates
       "already launched, don't relaunch for N minutes" — this can live in
       the new `FreshnessService`.
   - Call `jobService.runAsJob(updateCourseDataJobFactory.createForSubjectAndQuarterAndIfStale(subjectArea, quarterYYYYQ, true))`
     from the controller/service (this is exactly what
     `JobsController.launchUpdateCourseDataJob` already does, just called
     from an unauthenticated code path instead of an admin one).
   - Consider whether an anonymous/public trigger needs its own rate
     limiting layer (e.g. Spring `@RateLimiter` or a simple per-IP/global
     cap) to prevent abuse — the UCSB Developer API itself likely has rate
     limits, and `JobRateLimit` protects per-job pacing but not
     "how many jobs launch per minute from public traffic."

### Frontend changes

- `frontend/src/utils/*` — wherever `CourseOverTime*` results are fetched
  (search for the fetch helpers backing these four endpoints), update to
  read the new envelope shape.
- The relevant page components (search for pages that call
  courseovertime/description/buildingsearch — likely under
  `frontend/src/main/pages/`) need a banner/alert component, e.g.
  `DataFreshnessWarning.jsx`, shown when `staleOrMissingQuarters` is
  non-empty: *"Data for [quarter list] is not yet available for [subject].
  We've started loading it — please check back in a few minutes."*
- Add Cypress/RTL tests for: (a) normal case (no warning shown), (b) missing
  quarter (warning shown, correct quarter list rendered).

### Backend tests

- Unit tests for the new `FreshnessService` (stale, missing, all-fresh
  cases) — pattern after existing `IsStaleServiceTests`.
- Controller tests for each of the four controllers verifying the new
  response envelope and that a job gets launched (mock `JobService`) when
  data is missing — pattern after existing tests in
  `src/test/java/edu/ucsb/cs156/courses/controllers/CourseOverTime*Tests.java`.

---

## Part 2 (do second): Auto-upsert of live main-page results into MongoDB

**Goal:** every time a user searches the live main page
(`UCSBCurriculumController.primaries`, used by
`SectionSearchesIndexPageLoggedIn.jsx` / `...NotLoggedIn.jsx`), also persist
those results into `ConvertedSectionCollection` + `UpdateCollection`, same as
`UpdateCourseDataJob.updateCourses` already does.

### Backend changes

1. Extract the upsert logic currently embedded in
   `UpdateCourseDataJob.updateCourses` (lines 71-116 of
   `src/main/java/edu/ucsb/cs156/courses/jobs/UpdateCourseDataJob.java`) into
   a shared service, e.g. `CourseUpsertService.upsertConvertedSections(String
   subjectArea, String quarterYYYYQ, List<ConvertedSection> sections)`, so
   both `UpdateCourseDataJob` and the live controller can call it without
   duplicating the "find existing by quarter+enrollCode, update or insert,
   record counts, save an `Update`" logic. Have `UpdateCourseDataJob` call
   into this new service instead of doing it inline (keeps behavior
   identical, just DRYs it up) — this refactor should ship with its own
   passing existing job tests as a correctness check before wiring in the
   new caller.

2. In `UCSBCurriculumController.primaries` (or the `UCSBCurriculumService`
   layer it calls into — `getPrimaries`), after getting live `Primary`
   results, **also** fetch `getConvertedSections(dept, qtr, "A")` (same as
   the job does) and call the new upsert service. Two design options here —
   flag for the human/agent implementing this to decide with the team:
   - **(a) Synchronous inline upsert** — simplest, but adds Mongo write
     latency to every live page load, and duplicates an API call
     (`getPrimaries` and `getConvertedSections` currently hit UCSB's API
     independently with different parsing). Check whether `Primary` and
     `ConvertedSection` could be derived from a single underlying API
     response to avoid a second live HTTP call per request.
   - **(b) Fire-and-forget async job** — call
     `jobService.runAsJob(updateCourseDataJobFactory.createForSubjectAndQuarterAndIfStale(dept, qtr, false))`
     (note: `ifStale=false` so it always refreshes, matching "we just proved
     someone wants this data right now") without blocking the response.
     Keeps the main page fast, reuses 100% of existing job code, no new
     upsert service needed. **This is the simpler and lower-risk option** —
     recommend starting here, and only building the synchronous inline path
     if async proves to have unacceptable data-visibility lag for some use
     case.
   - Given the job infrastructure already exists end-to-end, **(b) requires
     no new persistence code at all** — just a call to
     `jobService.runAsJob(...)` added to the controller/service, plus the
     same launch-dedup/rate-limit concern noted in Part 1 (don't launch a
     fresh job on every single page hit for a popular subject/quarter;
     `ifStale`-gate it, or apply the same short-TTL guard).

3. Rate limiting / cost concern: the main page is the **highest-traffic**
   endpoint in the app. Launching a background job (even async) on every
   request multiplies UCSB Developer API traffic and Mongo writes
   significantly compared to today. Strongly recommend gating this by
   `IsStaleService.isStale(...)` first — i.e. only upsert if the existing
   data for that subject/quarter is actually stale/missing, not on every
   single request — which also means Part 2 depends on Part 1's
   `IsStaleService` usage patterns and should reuse rather than duplicate
   that check.

### Frontend changes

Likely none required — this is a backend-only side effect. Confirm no
frontend code needs to react to the write (e.g. no new loading state), since
the main page's own response shape doesn't need to change.

### Backend tests

- Extend `UCSBCurriculumControllerTests` (or equivalent) to verify a job
  gets launched (mock `JobService`) only when the queried subject/quarter is
  stale, not on every call.
- If extracting `CourseUpsertService`, add unit tests mirroring the existing
  `UpdateCourseDataJob` upsert tests, then confirm `UpdateCourseDataJob`'s
  existing test suite still passes unchanged after the refactor.

---

## Suggested acceptance criteria (to replace/extend the issue's current partial list)

**Part 1 — Freshness warning on MongoDB-backed pages**
- [ ] `CourseOverTimeController`, `CourseOverTimeInstructorController`,
      `CourseOverTimeDescriptionController`, and
      `CourseOverTimeBuildingController` report which quarters (if any) in
      the requested range are missing or stale for the requested subject
      area.
- [ ] When any quarter is missing/stale, a background `UpdateCourseDataJob`
      is launched for just that subject+quarter (deduplicated against
      concurrent/recent requests for the same combo).
- [ ] The frontend pages backed by these endpoints show a clear warning
      naming which quarters are not yet available and inviting the user to
      check back in a few minutes.
- [ ] Existing behavior (results for fresh data) is unchanged — no
      regression for the common case.

**Part 2 — Auto-upsert from the live main page**
- [ ] Searching the main page (`/api/public/primaries`) for a subject/quarter
      combo that is stale or missing triggers a background load into
      `ConvertedSectionCollection`/`UpdateCollection`, without blocking or
      slowing the user-visible response.
- [ ] Searching a subject/quarter combo that is already fresh does **not**
      trigger a redundant job launch.
- [ ] Main-page response format/latency is unaffected for the end user.

---

## Open questions for the team before implementation starts

1. Should the public-triggered job launches from Parts 1 and 2 share one
   dedup/rate-limit mechanism, or be independent? (Recommend: shared, since
   both key on the same `subjectArea+quarterYYYYQ`.)
2. Is there an existing per-IP or global API rate limiter in the app that
   the new public job-launch paths should register with, to avoid the
   live-API-upsert feature becoming a self-inflicted DoS vector during
   traffic spikes (e.g. first day of registration)?
3. Does the `docs/openapi.yaml` spec (if present/generated) need a review
   pass after the `CourseOverTime*` response envelope changes in Part 1?

**Comment by pconrad** [comment]
This issue has **not** been completed. I reviewed the very thorough implementation-plan comment already posted on this issue (by pconrad, earlier today) and re-verified its conclusions directly against the current code:

- `UCSBCurriculumController.primaries` / `.primariesGE` (`src/main/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumController.java`) call `ucsbCurriculumService.getPrimaries(...)` / `.getPrimariesByGE(...)` and return the result directly — there is no upsert into MongoDB (`ConvertedSectionCollection`/`UpdateCollection`) on these live-data code paths.
- `CourseOverTimeController` (and its sibling instructor/description/building controllers) contain no reference to `IsStaleService`, staleness, or freshness — they do not warn users when requested quarter/subject data hasn't been loaded into MongoDB yet.

So both behavioral asks in the acceptance criteria are still missing. However, as the earlier comment notes, the supporting infrastructure already exists and would only need to be wired up: an `Update`/`UpdateCollection` staleness-tracking table, an `IsStaleService`, and an `UpdateCourseDataJob` (reachable today only via an admin-only `JobsController` endpoint) that already contains the exact upsert logic this issue asks for. I was not able to find any merged PR that wires this infrastructure into the public-facing controllers described above — the feature remains unimplemented.

This comment was generated by Claude on 2026-08-18 in response to the following prompt:
> Please give your best assessment of whether this issue has already been completed by an earlier PR or PRs. If it is possible to identify the PRs, please link to it(them).
>
> If you are unable to determine whether the issue has been completed, simply state that.
