### ISSUE TITLE
EPIC: Add frontend for Jobs that don't have one

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156/proj-courses#92]
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

admin

### I can...

launch all jobs for which there are currently swagger endpoints

### So that...

launching jobs is more convenient

### Discussion

On the admin menu, there is a `Manage Jobs` item:

<img width="228" alt="image" src="https://github.com/ucsb-cs156/proj-courses/assets/1119017/dd4767ef-b97d-4a76-a82b-5a2907876e53">

That leads to this page:

<img width="1347" alt="image" src="https://github.com/ucsb-cs156/proj-courses/assets/1119017/a3c12005-f95c-4a86-a2da-0130abf9d10f">

However, at least one of these (Update Grade Data) is not implemneted:

<img width="565" alt="image" src="https://github.com/ucsb-cs156/proj-courses/assets/1119017/3b32bde6-519b-4b1b-9147-b6f6ee75fd86">

Implementing that can be an issue.

In addition, you can look at the jobs endpoints on Swagger:

<img width="1248" alt="image" src="https://github.com/ucsb-cs156/proj-courses/assets/1119017/5c6a02a2-bf9a-42bf-8de8-0a8cc66a7370">

If there are any remaining jobs for which there is an endpoint on swagger, but NOT a way for the admin to launch it from the menu, adding those can be an issue to work on.

### Acceptance Criteria

- [ ] There is a way for the admin to launch the `Load Grade Data` job from inside the app rather than having to go to swagger
- [ ] In general, there is a way for the admin to launch each of the jobs from inside the app rather than having to go to swagger

### Implementation Todos

Look at the code for existing jobs to see how to implement this.
